### ISSUE TITLE
all.equal in expected_encoding 

### ISSUE THREAD

**Issue by Sielinski** [jl5000/tidyged.io#2]
The expected_encoding function in tidyged.io throws the error "invalid argument type" because it uses !all.equal. The all.equal function doesn't return a true when the match fails, so the help file for all.equal offers this guidance: "Do not use all.equal directly in if expressions—either use isTRUE(all.equal(....)) or identical if appropriate."

**Comment by jl5000** [comment]
Thanks, good spot. I had no idea people were actually using this while I'm still developing it. I'll apply the fix tonight.
